# Generated by Django 3.2.5 on 2021-08-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockMarket', '0002_stock_name_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('enquery', models.TextField()),
                ('Stock_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_name', to='StockMarket.stock_name')),
            ],
            options={
                'ordering': ('user_name',),
            },
        ),
    ]
