# Generated by Django 3.2.5 on 2021-08-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMarket', '0004_alter_form_query_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_query',
            name='Stock_Name',
        ),
    ]
